units:
  pad: 2

  spacing: 0.75

  controllerW: 18.5
  controllerH: 33.5
  belowControllerH: 17
  caseBorder: 1.5
  screwThreadRadius: 0.5
  screwPCBRadius: 4.0

points:
    key.padding: cy
    zones:
        main:
            anchor:
                # Shift the PCB slightly to the right and down, otherwise it's weirdly positioned outside of the main sheet in KiCad
                shift: [100, -150]
            rows:
                bottom.row_net: P6
                home.row_net: P7
                top.row_net: P8
                num.row_net: P9
            columns:
                outer:
                    key:
                        col_net: P3
                        spread: cx
                        splay: 8
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_outer_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_home
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_outer_num
                        num:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_num
                pinky:
                    key:
                        col_net: P4
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_outer_bottom
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_bottom
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_outer_top
                        num:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_top
                ring:
                    key:
                        col_net: P5
                        stagger: cy-1
                        spread: cx+1
                        splay: -8
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_bottom
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_top
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_top
                        num:
                            led_in: "rgb_{{name}}"
                middle:
                    key:
                        col_net: P18
                        stagger: 2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_bottom
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_home
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_top
                        num:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_num
                index:
                    key:
                        col_net: P15
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_bottom
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_home
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_top
                        num:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_num
                inner:
                    key:
                        col_net: P14
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_home
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_num
                        num:
                            led_in: "rgb_{{name}}"    
                            led_out: rgb_main_index_num
        thumb:
            anchor:
                ref: main_inner_bottom
                shift: [0cx, -cy]
            rows.home.row_net: P16
            columns:
                outer.key:
                    col_net: P18
                    led_in: "rgb_{{name}}"
                    led_out: rgb_main_pinky_bottom
                    spread: cx
                home.key:
                    col_net: P15
                    led_in: "rgb_{{name}}"
                    led_out: rgb_thumb_outer_home
                    spread: cx + 2
                    rotate: -18
                    stagger: -3.2
                inner.key:
                    col_net: P14
                    led_in: P9
                    led_out: rgb_thumb_home_home
                    spread: cx
                    rotate: -36
                    stagger: -9.2
outlines:
    _board_outline:
        -   what: polygon
            fillet: 2
            points:
                -   ref: thumb_inner_home
                    shift: [0.6cx, 0.6cy]
                -   ref: thumb_inner_home
                    shift: [0.6cx, -0.6cy]
                -   ref: thumb_inner_home
                    shift: [-0.4cx, -0.6cy]

                -   ref: thumb_home_home
                    shift: [0.4cx, -0.6cy]
                -   ref: thumb_home_home
                    shift: [-0.4cx, -0.6cy]

                -   ref: thumb_outer_home
                    shift: [0.4cx, -0.6cy]
                -   ref: thumb_outer_home
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_middle_bottom
                    shift: [1.1cx, -1.5cy]
                -   ref: main_middle_bottom
                    shift: [-1cx, -1.5cy]

                -   ref: main_outer_bottom
                    shift: [1.6cx, -0.6cy]
                -   ref: main_outer_bottom
                    shift: [0.6cx, -0.6cy]
                -   ref: main_outer_bottom
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_outer_num
                    shift: [-0.6cx, 0.6cy]
                -   ref: main_outer_num
                    shift: [0.5cx, 0.6cy]

                -   ref: main_ring_num
                    shift: [-0.5cx, 0.6cy]
                -   ref: main_ring_num
                    shift: [0.4cx, 0.6cy]

                -   ref: main_middle_num
                    shift: [-0.4cx, 0.61cy]
                -   ref: main_middle_num
                    shift: [0.4cx, 0.6cy]

                -   ref: main_index_num
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_index_num
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_num
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_inner_num
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_num
                    shift: [0.6cx, 0.4cy]
                -   ref: main_inner_num
                    shift: [1.7cx, 0.4cy]
                -   ref: main_inner_bottom
                    shift: [1.7cx, -0.2cy]

                -   ref: thumb_inner_home
                    shift: [0cx, 0.6cy]
    _keycap_outlines:
        -   what: rectangle
            fillet: 2
            where: true
            size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
    preview:
        -   what: outline
            name: _board_outline
            operation: stack
        -   what: outline
            name: _keycap_outlines
            operation: stack
cases.speedy-o:
    -   what: outline
        name: _board_outline
        extrude: 3
        operation: subtract
    -   what: outline
        name: _keycap_outlines
        extrude: 6
        operation: add
pcbs.speedy-o:
    outlines:
        main.outline: _board_outline
        keycaps:
            outline: _keycap_outlines
            layer: Eco1.User
    footprints:
        led:
            what: sk6812mini
            where: true
            adjust:
                shift: [0, -5]
            params:
                din: "{{led_in}}"
                dout: "{{led_out}}"
                cutout: true
        diode:
            what: sod-123w
            where: true
            params:
                from: "{{name}}"
                to: "{{row_net}}"
            adjust:
                shift: [ -7.6, -1.6 ]
                rotate: 90
        choc:
            what: choc
            where: true
            params:
                keycaps: true
                reverse: true
                hotswap: true
                from: "{{col_net}}"
                to: "{{name}}"
        promicro_pretty:
            what: promicro_pretty
            where:
                ref: main_inner_top
            adjust:
                shift: [20, 7]
            params:
              reversable_pins: 13
                # rotate: -90
        jst-s2b-ph-kl:
            what: jst-s2b-ph-kl
            where:
                ref: main_inner_home
                shift: [0.6cx, -2]
                rotate: 180
            params:
                neg: GND
        pcm12:
            what: pcm12
            where:
                ref: main_inner_bottom
                shift: [1.57cx, 3]
                rotate: 90
            params:
                from: pos
                to: RAW
        reset:
            what: button
            params:
                from: GND
                to: RST
            where:
                ref.aggregate.parts: [main_inner_bottom]
                shift: [2*cx, 0]
                rotate: -90
        trrs:
            what: trrs_tight
            where:
                ref: main_inner_home
                shift: [1.65cx, -0.4cy]
                rotate: -90
            params:
                reverse: true
                symmetric: true
                # The naming of the nets on this footprint is different from the Corne schematics.
                A: ""
                B: VCC
                C: GND
                D: P10
        hole_top_left:
            what: mountingholem2
            where:
                ref: main_ring_num
                shift: [-0.8cx, 0]
        hole_bottom_left:
            what: mountingholem2
            where:
                ref: main_ring_bottom
                shift: [0, -1cy]
        hole_bottom_middle:
            what: mountingholem2
            where:
                ref: main_index_bottom
                shift: [0, -1cy]
        hole_bottom_right:
            what: mountingholem2
            where:
                ref: thumb_home_home
                shift: [0, 1cy]
        hole_top_right:
            what: mountingholem2
            where:
                ref: main_inner_top
                shift: [1.8cx, 0]
        front_text: &text
            what: text
            where: &textWhere
                ref: main_pinky_num
                shift: [0, 0.6cy]
            params: &textParams
                text: Speedy-O\nv0.1.0
                justify: left
        back_text:
            <<: *text
            where:
                <<: *textWhere
                shift: [0.4cx, 0.6cy]
            params:
                <<: *textParams
                layer: B.SilkS
                justify: left mirror
