units:
  px: cx + 2
  py: cy + 2


  pushX: (cx / 2)
  pushY: (cy / 2)

  padX: pushX + 2
  padY: pushY + 2

  pad: 2

  spacing: 0.75

  controllerW: 18.5
  controllerH: 33.5
  belowControllerH: 17
  caseBorder: 1.5
  screwThreadRadius: 0.5
  screwPCBRadius: 4.0
points:
  zones:
    matrix:
      columns:
        outer:
          key:
            spread: 0
            splay: 10
            column_net: P200
        pinky:
          key:
            spread: u
            splay: 0
            column_net: P201
        ring:
          key:
            spread: u+1
            stagger: cy+1/4
            splay: -10
            column_net: P202
        middle:
          key:
            shift: [0, 0]
            spread: u
            stagger: cx/3
            splay: 0
            column_net: P203
        index:
          key:
            spread: u
            stagger: -cy/3
            splay: 0
            column_net: P4
        inner:
          key:
            splay: 0
            spread: u
            stagger: -cy/6
            column_net: P5
      rows:
        bottom:
          row_net: P102
        home:
          row_net: P103
        top:
          row_net: P104
        num:
          row_net: P105
      anchor:
        # Shift the PCB slightly to the right and down, otherwise it's weirdly positioned outside of the main sheet in KiCad
        shift: [100, -150]
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-u/2
        ,-py-pad]
      columns:
        first:
          key:
            splay: -10
            width: 1.5u
          rows:
            home:
              column_net: P26
        second:
          key:
            spread: px*1.5-pad*2
            stagger: -pad
            splay: -10
          rows:
            home:
              column_net: P27
            upper:
              column_net: P24
        third:
          key:
            spread: px
            stagger: -pad
            splay: -10
          rows:
            home:
              column_net: P28
            upper:
              column_net: P25
outlines:
  keys:
    - what: rectangle
      where: true
      size: [14, 14]
      fillet: 0

  keys2:
    - what: rectangle
      where: true
      size: [cx, cy]
      fillet: 0
  board:
    - what: polygon
      operation: stack
      fillet: 4
      points:
        # Left
        - ref: matrix_outer_bottom
          shift: [-padX, -padY]

        # Top
        - ref: matrix_outer_num
          shift: [-padX, padY]
        - ref: matrix_middle_num
          shift: [-px, padY]
        - ref: matrix_middle_num
          shift: [2*px+padX, padY]
        # Rigth
        - ref: matrix_middle_num
          shift: [2*px+padX, -padY]
        - ref: matrix_middle_num
          shift: [5.3*cx, -padY]
        - ref: matrix_middle_num
          shift: [5.3*cx, -4.4*py]
          # Bottom
        - ref: thumb_third_home
          shift: [padX, -padY]
        - ref: thumb_third_home
          shift: [-pushX+pad, -padY]
        - ref: thumb_second_home
          shift: [pushX-pad, -padY]
        - ref: thumb_second_home
          shift: [-pushX, -padY]
        - ref: thumb_first_home
          shift: [padX, -padY]
        - ref: thumb_first_home
          shift: [-padX, -padY]

        - ref: matrix_pinky_bottom
          shift: [padX, -padY]
        # Connect to Left
        - ref: matrix_outer_bottom
          shift: [-padX, -padY]
  board_key_cutouts:
    - name: board
    - operation: subtract
      name: keys