
points:
  zones:
    matrix:
      columns:
        outer:
          key:
            spread: 0
            splay: 10
            origin: [0, -17]
          rows:
            bottom:
              bind: [5, 0, 0, 0]
              column_net: P18
            home:
              bind: [0, 12, 0, 0]
              column_net: P12
            top:
              bind: [0, 8, 5, 0]
              column_net: P6
            number:
              bind: [0, 6, 0, 0]
              column_net: P0
        pinky:
          key:
            spread: u
            splay: 0
            origin: [0, 0]
          rows:
            bottom:
              bind: [5, 0, 0, 0]
              column_net: P19
            home:
              bind: [0, 12, 0, 0]
              column_net: P13
            top:
              bind: [0, 8, 5, 0]
              column_net: P7
            number:
              bind: [0, 6, 0, 0]
              column_net: P1
        ring:
          key:
            spread: u+1
            stagger: 17
            splay: -10
            origin: [0, 0]
          rows:
            bottom:
              bind: [0, 0, 2, 10]
              column_net: P20
            home:
              bind: [5, 0, 5, 0]
              column_net: P14
            top:
              bind: [0, 6, 0, 0]
              column_net: P8
            number:
              bind: [0, 6, 0, 0]
              column_net: P2
        middle:
          key:
            shift: [0, 0]
            spread: u
            stagger: 17/3
            splay: 0
            origin: [0, -17]
          rows:
            bottom:
              bind: [0, 10, 0, 5]
              column_net: P21
            home:
              bind: 5
              column_net: P15
            top:
              bind: [0, 0, 0, 0]
              column_net: P9
            number:
              bind: [0, 0, 0, 0]
              column_net: P3
        index:
          key:
            spread: u
            stagger: -17/3
            splay: 0
            origin: [0, -17]
          rows:
            bottom:
              bind: [0, 5, 0, 0]
              column_net: P22
            home:
              bind: [5, 0, 5, 0]
              column_net: P16
            top:
              bind: [0, 0, 0, 6]
              column_net: P10
            number:
              bind: [0, 0, 0, 6]
              column_net: P4
        inner:
          key:
            splay: 0
            spread: u
            stagger: -17/6
            origin: [0, -17]
          rows: 
            bottom:
              bind: [5, 19, 20, 2]
              column_net: P23
            home:
              bind: [0, 27, 0, 5]
              column_net: P17
            top:
              bind: [0, 0, 5, 5]
              column_net: P11
            number:
              bind: [0, 0, 5, 5]
              column_net: P5
      rows:
        bottom:
          padding: 17
        home:
          padding: 17
        top:
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [0,-24]
      columns:
        first:
          key:
            splay: -15
          rows:
            home:
              column_net: P26
              bind: [10, 1, 0, 70]
        second:
          key:
            spread: 18
            splay: -10
            origin: [-9, -9.5]
          rows:
            home:
              column_net: P27
              bind: [0, 0, 0, 5]
            upper:
              column_net: P24
              bind: [0, 0, 0, 5]
        third:
          key:
            spread: 18
            splay: -10
            origin: [-9, -9.5]
          rows:
            home:
              column_net: P28
              bind: [0, 0, 0, 5]
            upper:
              column_net: P25
              bind: [0, 0, 0, 5]
outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      asym: left
      size: [18,17]
      corner: 1
  first:
    - what: outline
      name: raw
      fillet: 3
  second:
    - what: outline
      name: first
      fillet: 2
  third:
    - what: outline
      name: second
      fillet: 1
  panel:
    - what: outline
      name: third
      fillet: 0.5
  pcb-outline:
    - what: polygon
      name: pcb-outline
      operation: stack
      fillet: 2
pcbs:
  speedy-o:
    outlines:
      main:
        outline: pcb-outline
    footprints:
      choc:
        what: choc
        where: true
        adjust:
          rotate: 180
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          keycaps: true
          reverse: true
      choc_hotswap:
        what: choc
        where: /^matrix_.*/
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
        # Rotate the key switches upside-down (easier to fit controller that way)
          rotate: 180
      # Main diodes
      diode_main:
        what: diode
        where: /^matrix_(?!(?:sixth_top|sixth_home|third_home|first_num|first_bottom|fourth_top|fourth_mod)).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -3.5]
          rotate: 90
      # Move a diode so it doesn't conflict with controller
      diode_weird1:
        what: diode
        where: matrix_sixth_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -16.0]
          rotate: 90
      # Move another diode so it doesn't conflict with controller
      diode_weird2:
        what: diode
        where: matrix_sixth_home
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -9.5]
          rotate: 90
      # Move some other diodes so they don't conflict with mounting holes
      diode_mounting_hole_conflict1:
        what: diode
        where: /^matrix_(?:third_home|first_num|first_bottom)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, 3.5]
          rotate: 90
      diode_mounting_hole_conflict2:
        what: diode
        where: /^matrix_(?:fourth_top|fourth_mod)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -4.5]
          rotate: 90
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_sixth_num
          shift: [-9, -1.5]
          rotate: -180.0
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_fourth_home
          shift: [-7, 5.5]
          rotate: 90
        params:
            side: B
            pos: pos
            neg: GND
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: EVQPUC
        params: 
          side: B
          from: GND
          to: RST 
        where:
          ref: matrix_sixth_top
          shift: [9.0, 2.8]
          rotate: -90.0
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
            ref: matrix_sixth_top
            shift: [8.8, -6.0]
            rotate: -90
        params:
            side: B
            from: pos
            to: RAW
      # Mounting holes
      hole_bottom_right:
        what: mountinghole
        where:
          ref: matrix_fifth_mod
          shift: [-pushX, pushY]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: matrix_first_bottom
          shift: [pushX, -pushY]
      hole_top_left:
        what: mountinghole
        where:
          ref: matrix_second_num
          shift: [-pushX, -pushY]
      hole_top_right:
        what: mountinghole
        where:
          ref: matrix_fifth_top
          shift: [-pushX, pushY]
      hole_center:
        what: mountinghole
        where:
          ref: matrix_fourth_bottom
          shift: [-pushX, pushY]
      # Write "Caldera" on the PCB
      front_text: &text
        what: text
        where: &textWhere
            ref: matrix_fourth_num
            shift: [-8.7, 5.5]
        params: &textParams
            text: Caldera
            justify: left
            h_size: 3.0
            v_size: 3.0
            thickness: 0.4

